CREATE TYPE "public"."conversation_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TYPE "public"."message_role" AS ENUM('user', 'assistant', 'system');--> statement-breakpoint
CREATE TABLE "joanna_conversation" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid,
	"backboardThreadId" varchar(255) NOT NULL,
	"title" varchar(500),
	"status" "conversation_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "joanna_conversation_backboardThreadId_unique" UNIQUE("backboardThreadId")
);
--> statement-breakpoint
CREATE TABLE "joanna_message" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversationId" uuid NOT NULL,
	"role" "message_role" NOT NULL,
	"content" text NOT NULL,
	"metadata" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "joanna_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "joanna_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "joanna_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(255) NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "joanna_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "joanna_conversation" ADD CONSTRAINT "joanna_conversation_userId_joanna_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."joanna_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "joanna_message" ADD CONSTRAINT "joanna_message_conversationId_joanna_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."joanna_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversation_user_idx" ON "joanna_conversation" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "conversation_backboard_thread_idx" ON "joanna_conversation" USING btree ("backboardThreadId");--> statement-breakpoint
CREATE INDEX "conversation_status_idx" ON "joanna_conversation" USING btree ("status");--> statement-breakpoint
CREATE INDEX "message_conversation_idx" ON "joanna_message" USING btree ("conversationId");--> statement-breakpoint
CREATE INDEX "message_created_at_idx" ON "joanna_message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "name_idx" ON "joanna_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "joanna_user" USING btree ("email");